CREATE TABLE parent(id INTEGER PRIMARY KEY);
CREATE TABLE child(id INTEGER, pid INTEGER, FOREIGN KEY (pid) REFERENCES parent(id));
INSERT INTO parent VALUES (1), (2);
INSERT INTO child VALUES (10, 1), (11, 2);
SELECT pid FROM child ORDER BY pid
