PRAGMA foreign_keys = ON;
CREATE TABLE parent(id INTEGER PRIMARY KEY);
CREATE TABLE child(id INTEGER, pid INTEGER REFERENCES parent(id) ON DELETE CASCADE);
INSERT INTO parent VALUES (1), (2);
INSERT INTO child VALUES (10, 1), (11, 2);
DELETE FROM parent WHERE id = 1;
SELECT id, pid FROM child ORDER BY id
