//! SQLite scalar function parity tests.
//!
//! These tests compare RedlineDB against the bundled rusqlite oracle. For
//! nondeterministic functions such as `randomblob`, the query projects stable
//! properties like type and length instead of comparing generated bytes.

#[path = "parity_oracle/harness.rs"]
mod harness;

fn assert_scalar_parity(sql: &str) {
    harness::assert_parity(sql);
}

// -- substr -----------------------------------------------------------------

#[test]
fn substr_basic_1based() {
    assert_scalar_parity("SELECT substr('hello', 2)");
}

#[test]
fn substr_with_length() {
    assert_scalar_parity("SELECT substr('hello', 2, 3)");
}

#[test]
fn substr_negative_start() {
    assert_scalar_parity("SELECT substr('hello', -3)");
}

#[test]
fn substr_zero_start_acts_as_one() {
    assert_scalar_parity("SELECT substr('hello', 0, 3)");
}

#[test]
fn substr_null_propagates() {
    assert_scalar_parity("SELECT substr(NULL, 1), substr('hi', NULL)");
}

#[test]
fn substr_alias_substring() {
    assert_scalar_parity("SELECT substring('hello', 2, 3)");
}

#[test]
fn substr_beyond_length_returns_empty() {
    assert_scalar_parity("SELECT substr('hi', 10)");
}

// -- instr ------------------------------------------------------------------

#[test]
fn instr_found() {
    assert_scalar_parity("SELECT instr('hello world', 'world')");
}

#[test]
fn instr_not_found() {
    assert_scalar_parity("SELECT instr('hello', 'xyz')");
}

#[test]
fn instr_null_propagates() {
    assert_scalar_parity("SELECT instr(NULL, 'x'), instr('x', NULL)");
}

#[test]
fn instr_empty_needle_returns_one() {
    assert_scalar_parity("SELECT instr('hello', '')");
}

// -- trim / ltrim / rtrim ----------------------------------------------------

#[test]
fn trim_whitespace() {
    assert_scalar_parity("SELECT trim('  hello  ')");
}

#[test]
fn trim_custom_chars() {
    assert_scalar_parity("SELECT trim('***hello***', '*')");
}

#[test]
fn ltrim_whitespace() {
    assert_scalar_parity("SELECT ltrim('  hi  ')");
}

#[test]
fn rtrim_whitespace() {
    assert_scalar_parity("SELECT rtrim('  hi  ')");
}

#[test]
fn trim_null_propagates() {
    assert_scalar_parity("SELECT trim(NULL)");
}

// -- replace ----------------------------------------------------------------

#[test]
fn replace_basic() {
    assert_scalar_parity("SELECT replace('hello world', 'world', 'Rust')");
}

#[test]
fn replace_all_occurrences() {
    assert_scalar_parity("SELECT replace('aababab', 'ab', 'X')");
}

#[test]
fn replace_null_propagates() {
    assert_scalar_parity(
        "SELECT replace(NULL, 'a', 'b'), replace('a', NULL, 'b'), replace('a', 'a', NULL)",
    );
}

// -- printf / format ---------------------------------------------------------

#[test]
fn printf_string_placeholder() {
    assert_scalar_parity("SELECT printf('Hello, %s!', 'world')");
}

#[test]
fn printf_integer_placeholder() {
    assert_scalar_parity("SELECT printf('%d bottles', 99)");
}

#[test]
fn printf_hex_placeholder() {
    assert_scalar_parity("SELECT printf('%x', 255)");
}

#[test]
fn printf_percent_escape() {
    assert_scalar_parity("SELECT printf('100%%')");
}

#[test]
fn format_is_alias_for_printf() {
    assert_scalar_parity("SELECT format('%d + %d = %d', 1, 2, 3)");
}

#[test]
fn printf_null_format_returns_null() {
    assert_scalar_parity("SELECT printf(NULL)");
}

// -- iif --------------------------------------------------------------------

#[test]
fn iif_true_branch() {
    assert_scalar_parity("SELECT iif(1, 'yes', 'no')");
}

#[test]
fn iif_false_branch() {
    assert_scalar_parity("SELECT iif(0, 'yes', 'no')");
}

#[test]
fn iif_null_condition_returns_false_branch() {
    assert_scalar_parity("SELECT iif(NULL, 'yes', 'no')");
}

// -- sign -------------------------------------------------------------------

#[test]
fn sign_positive() {
    assert_scalar_parity("SELECT sign(42)");
}

#[test]
fn sign_negative() {
    assert_scalar_parity("SELECT sign(-7)");
}

#[test]
fn sign_zero() {
    assert_scalar_parity("SELECT sign(0)");
}

#[test]
fn sign_null() {
    assert_scalar_parity("SELECT sign(NULL)");
}

// -- char -------------------------------------------------------------------

#[test]
fn char_basic_ascii() {
    assert_scalar_parity("SELECT char(72, 105)");
}

#[test]
fn char_single() {
    assert_scalar_parity("SELECT char(65)");
}

// -- unicode ----------------------------------------------------------------

#[test]
fn unicode_basic() {
    assert_scalar_parity("SELECT unicode('A')");
}

#[test]
fn unicode_multi_char_returns_first() {
    assert_scalar_parity("SELECT unicode('Hello')");
}

#[test]
fn unicode_null_propagates() {
    assert_scalar_parity("SELECT unicode(NULL)");
}

// -- zeroblob ---------------------------------------------------------------

#[test]
fn zeroblob_correct_length() {
    assert_scalar_parity("SELECT zeroblob(5)");
}

#[test]
fn zeroblob_zero_length() {
    assert_scalar_parity("SELECT zeroblob(0)");
}

#[test]
fn zeroblob_null_propagates() {
    assert_scalar_parity("SELECT zeroblob(NULL)");
}

// -- randomblob -------------------------------------------------------------

#[test]
fn randomblob_correct_length() {
    assert_scalar_parity("SELECT typeof(randomblob(16)), length(randomblob(16))");
}

#[test]
fn randomblob_produces_blob_of_right_size() {
    assert_scalar_parity("SELECT typeof(randomblob(8)), length(randomblob(8))");
}

// -- functions in column expressions after INSERT ---------------------------

#[test]
fn scalar_funcs_in_select_after_insert() {
    assert_scalar_parity(
        "CREATE TABLE t(name TEXT);
         INSERT INTO t VALUES ('  hello  ');
         SELECT trim(name) FROM t",
    );
}

#[test]
fn replace_in_where_clause() {
    assert_scalar_parity(
        "CREATE TABLE t(id INTEGER, val TEXT);
         INSERT INTO t VALUES (1, 'foo'), (2, 'bar');
         SELECT id FROM t WHERE replace(val, 'foo', 'baz') = 'baz'",
    );
}

// -- real to text coercion parity -------------------------------------------

#[test]
fn lower_upper_of_real_keeps_trailing_zero() {
    for v in [1.0f64, 22.0, 7.0, 1.5, 12.25] {
        assert_scalar_parity(&format!("SELECT lower(CAST({v} AS REAL))"));
        assert_scalar_parity(&format!("SELECT upper(CAST({v} AS REAL))"));
    }
}

#[test]
fn cast_real_as_text_keeps_trailing_zero() {
    for v in [1.0f64, 0.0, -3.0, 22.5, 100.0] {
        assert_scalar_parity(&format!("SELECT CAST(CAST({v} AS REAL) AS TEXT)"));
    }
}
