CREATE TABLE a(v INTEGER);
CREATE TABLE b(v INTEGER);
CREATE TABLE c(v INTEGER);
INSERT INTO a VALUES (1);
INSERT INTO b VALUES (2);
INSERT INTO c VALUES (3);
SELECT v FROM a UNION ALL SELECT v FROM b UNION ALL SELECT v FROM c ORDER BY v
