CREATE TABLE t(id INTEGER, v INTEGER);
CREATE TABLE log(id INTEGER, old_v INTEGER);
INSERT INTO t VALUES (1, 100), (2, 200);
CREATE TRIGGER trg BEFORE DELETE ON t FOR EACH ROW BEGIN INSERT INTO log VALUES (OLD.id, OLD.v); END;
DELETE FROM t WHERE id = 1;
SELECT id, old_v FROM log ORDER BY id
