CREATE TABLE t(id INTEGER, v INTEGER);
CREATE TABLE log(id INTEGER, before INTEGER, after INTEGER);
INSERT INTO t VALUES (1, 10);
CREATE TRIGGER trg AFTER UPDATE ON t FOR EACH ROW BEGIN INSERT INTO log VALUES (NEW.id, OLD.v, NEW.v); END;
UPDATE t SET v = 99 WHERE id = 1;
SELECT id, before, after FROM log
