CREATE TABLE t(id INTEGER, v INTEGER);
CREATE TABLE log(msg TEXT);
CREATE TRIGGER trg AFTER INSERT ON t FOR EACH ROW WHEN NEW.v > 100 BEGIN INSERT INTO log VALUES ('big'); END;
INSERT INTO t VALUES (1, 50);
INSERT INTO t VALUES (2, 500);
SELECT msg FROM log
