CREATE TABLE t(id INTEGER);
CREATE TABLE cnt(c INTEGER);
INSERT INTO cnt VALUES (0);
CREATE TRIGGER trg AFTER INSERT ON t BEGIN UPDATE cnt SET c = c + 1; END;
INSERT INTO t VALUES (1);
INSERT INTO t VALUES (2);
INSERT INTO t VALUES (3);
SELECT c FROM cnt
