use super::text::escape_xml;

#[derive(Debug, Clone, PartialEq)]
pub(crate) struct PerformanceHistogram {
    pub(crate) case_count: usize,
    pub(crate) min_pct: f64,
    pub(crate) median_pct: f64,
    pub(crate) max_pct: f64,
    pub(crate) buckets: Vec<HistogramBucket>,
}

#[derive(Debug, Clone, PartialEq)]
pub(crate) struct HistogramBucket {
    pub(crate) label: &'static str,
    pub(crate) short_label: &'static str,
    pub(crate) lower_pct: Option<f64>,
    pub(crate) upper_pct: Option<f64>,
    pub(crate) count: usize,
}

#[derive(Debug, Clone, Copy)]
struct BucketSpec {
    label: &'static str,
    short_label: &'static str,
    lower_pct: Option<f64>,
    upper_pct: Option<f64>,
}

const BUCKET_SPECS: [BucketSpec; 9] = [
    BucketSpec {
        label: "< -50%",
        short_label: "<-50",
        lower_pct: None,
        upper_pct: Some(-50.0),
    },
    BucketSpec {
        label: "-50% to -25%",
        short_label: "-50..-25",
        lower_pct: Some(-50.0),
        upper_pct: Some(-25.0),
    },
    BucketSpec {
        label: "-25% to 0%",
        short_label: "-25..0",
        lower_pct: Some(-25.0),
        upper_pct: Some(0.0),
    },
    BucketSpec {
        label: "0% to 25%",
        short_label: "0..25",
        lower_pct: Some(0.0),
        upper_pct: Some(25.0),
    },
    BucketSpec {
        label: "25% to 50%",
        short_label: "25..50",
        lower_pct: Some(25.0),
        upper_pct: Some(50.0),
    },
    BucketSpec {
        label: "50% to 75%",
        short_label: "50..75",
        lower_pct: Some(50.0),
        upper_pct: Some(75.0),
    },
    BucketSpec {
        label: "75% to 100%",
        short_label: "75..100",
        lower_pct: Some(75.0),
        upper_pct: Some(100.0),
    },
    BucketSpec {
        label: "100% to 150%",
        short_label: "100..150",
        lower_pct: Some(100.0),
        upper_pct: Some(150.0),
    },
    BucketSpec {
        label: ">= 150%",
        short_label: ">=150",
        lower_pct: Some(150.0),
        upper_pct: None,
    },
];

pub(crate) fn build<I>(improvements: I) -> PerformanceHistogram
where
    I: IntoIterator<Item = f64>,
{
    let mut values = improvements.into_iter().collect::<Vec<_>>();
    values.sort_by(f64::total_cmp);

    let mut buckets = BUCKET_SPECS
        .iter()
        .map(|spec| HistogramBucket {
            label: spec.label,
            short_label: spec.short_label,
            lower_pct: spec.lower_pct,
            upper_pct: spec.upper_pct,
            count: 0,
        })
        .collect::<Vec<_>>();

    for value in &values {
        let index = BUCKET_SPECS
            .iter()
            .position(|spec| bucket_contains(*spec, *value))
            .expect("fixed histogram buckets cover all f64 percentage values");
        buckets[index].count = buckets[index].count.saturating_add(1);
    }

    let case_count = values.len();
    debug_assert_eq!(
        buckets.iter().map(|bucket| bucket.count).sum::<usize>(),
        case_count
    );

    let min_pct = values.first().copied().unwrap_or(0.0);
    let median_pct = values.get(values.len() / 2).copied().unwrap_or(0.0);
    let max_pct = values.last().copied().unwrap_or(0.0);
    PerformanceHistogram {
        case_count,
        min_pct,
        median_pct,
        max_pct,
        buckets,
    }
}

fn bucket_contains(spec: BucketSpec, value: f64) -> bool {
    let lower_ok = spec.lower_pct.is_none_or(|lower| value >= lower);
    let upper_ok = spec.upper_pct.is_none_or(|upper| value < upper);
    lower_ok && upper_ok
}

pub(crate) fn svg(histogram: &PerformanceHistogram, updated_date: &str) -> String {
    let width = 760.0;
    let height = 236.0;
    let left = 58.0;
    let right = 24.0;
    let top = 72.0;
    let bottom = 46.0;
    let plot_w = width - left - right;
    let plot_h = height - top - bottom;
    let axis_y = top + plot_h;
    let max_count = histogram
        .buckets
        .iter()
        .map(|bucket| bucket.count)
        .max()
        .unwrap_or(0)
        .max(1) as f64;
    let bar_gap = 8.0;
    let bar_w = (plot_w - bar_gap * (histogram.buckets.len().saturating_sub(1) as f64))
        / histogram.buckets.len().max(1) as f64;
    let mut out = String::from(
        "<!-- Generated by: redlinedb-bench sqlite_parity report -->\n<!-- Source: benchmark-results/sqlite-parity/latest/raw.jsonl -->\n<!-- Command: just sqlite-parity-report-update -->\n<!-- DO NOT EDIT BY HAND. -->\n",
    );
    out.push_str(&format!(
        r##"<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}" role="img" aria-labelledby="perf-hist-title perf-hist-desc">
<title id="perf-hist-title">SQLite parity performance distribution, Updated {}</title>
<desc id="perf-hist-desc">Fixed-bucket distribution of measured case median latency improvement versus SQLite. Cases: {}; min {:.2}%, median {:.2}%, max {:.2}%.</desc>
<rect width="{width}" height="{height}" fill="#ffffff"/>
<text x="{left}" y="26" font-family="sans-serif" font-size="17" font-weight="700" fill="#111827">Performance distribution</text>
<text x="{left}" y="47" font-family="sans-serif" font-size="12" fill="#374151">Measured case medians only; warmup samples excluded; fixed buckets preserve report-to-report comparability.</text>
<text x="{left}" y="64" font-family="sans-serif" font-size="12" fill="#111827">cases {} | min {:.2}% | median {:.2}% | max {:.2}%</text>
<line x1="{left}" y1="{axis_y}" x2="{:.2}" y2="{axis_y}" stroke="#4b5563"/>
<line x1="{left}" y1="{top}" x2="{left}" y2="{axis_y}" stroke="#4b5563"/>
"##,
        updated_date,
        histogram.case_count,
        histogram.min_pct,
        histogram.median_pct,
        histogram.max_pct,
        histogram.case_count,
        histogram.min_pct,
        histogram.median_pct,
        histogram.max_pct,
        left + plot_w
    ));

    for tick in [0.25, 0.5, 0.75, 1.0] {
        let y = axis_y - tick * plot_h;
        out.push_str(&format!(
            r##"<line x1="{left}" y1="{y:.2}" x2="{:.2}" y2="{y:.2}" stroke="#e5e7eb"/>
"##,
            left + plot_w
        ));
    }

    for (index, bucket) in histogram.buckets.iter().enumerate() {
        let x = left + index as f64 * (bar_w + bar_gap);
        let bar_h = bucket.count as f64 / max_count * plot_h;
        let y = axis_y - bar_h;
        let count_y = (y - 5.0).max(top + 10.0);
        out.push_str(&format!(
            r##"<rect x="{x:.2}" y="{y:.2}" width="{bar_w:.2}" height="{bar_h:.2}" rx="2" fill="{}"><title>{}: {} cases</title></rect>
<text x="{:.2}" y="{count_y:.2}" font-family="sans-serif" font-size="10" fill="#111827" text-anchor="middle">{}</text>
<text x="{:.2}" y="{:.2}" font-family="sans-serif" font-size="10" fill="#374151" text-anchor="middle">{}</text>
"##,
            bucket_color(bucket),
            escape_xml(bucket.label),
            bucket.count,
            x + bar_w / 2.0,
            bucket.count,
            x + bar_w / 2.0,
            axis_y + 16.0,
            escape_xml(bucket.short_label)
        ));
    }

    out.push_str(
        r##"<text x="18" y="132" font-family="sans-serif" font-size="12" fill="#374151" transform="rotate(-90 18 132)" text-anchor="middle">case count</text>
</svg>
"##,
    );
    out
}

fn bucket_color(bucket: &HistogramBucket) -> &'static str {
    match (bucket.lower_pct, bucket.upper_pct) {
        (_, Some(upper)) if upper <= 0.0 => "#dc2626",
        (Some(lower), _) if lower >= 75.0 => "#1d4ed8",
        (Some(lower), _) if lower >= 50.0 => "#2563eb",
        (Some(lower), _) if lower >= 25.0 => "#059669",
        _ => "#16a34a",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fixed_bins_count_each_measured_case_once() {
        let histogram = build([-90.0, -50.0, -1.0, 0.0, 24.99, 25.0, 50.0, 75.0, 150.0]);
        let bucket_counts = histogram
            .buckets
            .iter()
            .map(|bucket| bucket.count)
            .collect::<Vec<_>>();

        assert_eq!(histogram.case_count, 9);
        assert_eq!(bucket_counts, vec![1, 1, 1, 2, 1, 1, 1, 0, 1]);
        assert_eq!(
            histogram
                .buckets
                .iter()
                .map(|bucket| bucket.count)
                .sum::<usize>(),
            histogram.case_count
        );
    }

    #[test]
    fn stats_are_sorted_from_measured_values() {
        let histogram = build([75.0, 10.0, -25.0, 50.0, 0.0]);

        assert_eq!(histogram.min_pct, -25.0);
        assert_eq!(histogram.median_pct, 10.0);
        assert_eq!(histogram.max_pct, 75.0);
    }

    #[test]
    fn svg_has_accessible_title_and_light_background() {
        let histogram = build([25.0, 50.0, 75.0]);
        let svg = svg(&histogram, "2026-05-21");

        assert!(svg.contains("<title id=\"perf-hist-title\">"));
        assert!(svg.contains("<desc id=\"perf-hist-desc\">"));
        assert!(svg.contains("&lt;-50"));
        assert!(svg.contains("fill=\"#ffffff\""));
        assert!(svg.contains("fill=\"#111827\""));
    }
}
