//! D6 FFI symbol-diff: compute `(libsqlite3 public symbols) - (RedlineDB
//! exports) - (allowlist)`. The set must be empty.
//!
//! Inputs:
//!   - `target/proof/sqlite-full-parity/libsqlite3-symbols.txt` — pinned
//!     reference list generated by `scripts/parity/dump-sqlite-symbols.sh`
//!     against `libsqlite3-sys` 0.35.0 (the version `rusqlite` 0.37.0 pulls
//!     in as a dev-dependency).
//!   - `crates/ffi/tests/symbol_allowlist.toml` — strict-justification
//!     allowlist for libsqlite3 symbols that RedlineDB does NOT export.
//!   - `target/debug/libredlinedb.{dylib,so}` — the just-built cdylib whose
//!     exported `sqlite3_*` symbols are diffed against the reference.
//!
//! If the diff is non-empty, the test prints each missing symbol and the
//! remediation hint: either implement the symbol (preferred) or add an
//! entry to `symbol_allowlist.toml` with a strict justification per the
//! file's header policy.
//!
//! Initial state: many symbols are missing because workstreams B1-B5 are
//! still in flight. The initial diff baseline is captured at
//! `target/proof/sqlite-full-parity/symbol-diff-baseline.txt` on first run.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};
use std::process::Command;

const REFERENCE_PATH: &str = "target/proof/sqlite-full-parity/libsqlite3-symbols.txt";
const ALLOWLIST_PATH: &str = "crates/ffi/tests/symbol_allowlist.toml";
const BASELINE_PATH: &str = "target/proof/sqlite-full-parity/symbol-diff-baseline.txt";

/// Compute the workspace root by walking up from `CARGO_MANIFEST_DIR`. The
/// integration test runs from `crates/ffi/`, so the workspace root is two
/// `parent()` steps away.
fn workspace_root() -> PathBuf {
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    PathBuf::from(manifest_dir)
        .parent()
        .and_then(Path::parent)
        .expect("workspace root above crates/ffi")
        .to_path_buf()
}

fn load_reference(path: &Path) -> BTreeSet<String> {
    let text = std::fs::read_to_string(path).unwrap_or_else(|err| {
        panic!(
            "missing libsqlite3 reference list at {}: {err}\n\
             hint: run `bash scripts/parity/dump-sqlite-symbols.sh` once",
            path.display()
        )
    });
    text.lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .map(ToOwned::to_owned)
        .collect()
}

/// Tiny TOML parser dedicated to the `[[exclude]] symbol = "X"` rows. We
/// intentionally do not pull in a TOML crate: keeping `redlinedb-ffi` zero
/// new dev-dependency-cost preserves the build-speed invariant the jankurai
/// audit rubric tracks.
fn load_allowlist(path: &Path) -> BTreeSet<String> {
    let text = std::fs::read_to_string(path).unwrap_or_else(|err| {
        panic!(
            "missing allowlist at {}: {err}\n\
             hint: every excluded libsqlite3 symbol needs a one-line justification",
            path.display()
        )
    });
    let mut out = BTreeSet::new();
    for line in text.lines() {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix("symbol") {
            // form: `symbol = "sqlite3_..."`
            let after_eq = rest.split_once('=').map(|(_, v)| v.trim()).unwrap_or("");
            if let Some(first_q) = after_eq.find('"') {
                let after = &after_eq[first_q + 1..];
                if let Some(end_q) = after.find('"') {
                    let name = after[..end_q].trim();
                    if !name.is_empty() {
                        out.insert(name.to_owned());
                    }
                }
            }
        }
    }
    out
}

fn dylib_extension() -> &'static str {
    if cfg!(target_os = "macos") {
        "dylib"
    } else if cfg!(target_os = "windows") {
        "dll"
    } else {
        "so"
    }
}

fn find_dylib(workspace: &Path) -> PathBuf {
    let ext = dylib_extension();
    // The integration test is built by `cargo test -p redlinedb-ffi`. The
    // cdylib lives at `target/debug/libredlinedb.<ext>` (or
    // `target/release/libredlinedb.<ext>` if the test was invoked under
    // --release). Prefer release first to match `just fuzz-parity-nightly`.
    for profile in ["release", "debug"] {
        let candidate = workspace
            .join("target")
            .join(profile)
            .join(format!("libredlinedb.{ext}"));
        if candidate.exists() {
            return candidate;
        }
    }
    panic!(
        "libredlinedb.{ext} not found under target/{{debug,release}}; \
         run `cargo build -p redlinedb-ffi` first"
    );
}

fn dylib_exports(dylib: &Path) -> BTreeSet<String> {
    // macOS / Linux: `nm -gU` lists external defined symbols. On Linux we
    // prefer `-D --defined-only` because `-U` is mac-specific (means
    // "undefined only" on GNU binutils). Use `--extern-only --defined-only`
    // on Linux and `nm -gU` on macOS to get the same effective set.
    let output = if cfg!(target_os = "macos") {
        Command::new("nm")
            .arg("-gU")
            .arg(dylib)
            .output()
            .expect("nm -gU on macOS")
    } else {
        Command::new("nm")
            .args(["-D", "--defined-only", "--extern-only"])
            .arg(dylib)
            .output()
            .expect("nm -D --defined-only --extern-only on Linux")
    };
    assert!(
        output.status.success(),
        "nm exited non-zero on {}: {}",
        dylib.display(),
        String::from_utf8_lossy(&output.stderr)
    );
    let stdout = String::from_utf8(output.stdout).expect("nm output is UTF-8");

    let mut out = BTreeSet::new();
    for line in stdout.lines() {
        // mach-o lines: `<addr> <type> _sqlite3_...`. ELF lines:
        // `<addr> <type> sqlite3_...`. Use rsplit on whitespace to get the
        // symbol token then strip the leading underscore on macOS.
        let symbol = match line.split_whitespace().last() {
            Some(s) => s,
            None => continue,
        };
        let stripped = symbol.strip_prefix('_').unwrap_or(symbol);
        if stripped.starts_with("sqlite3_") {
            out.insert(stripped.to_owned());
        }
    }
    out
}

/// Excluded from the default `cargo test -p redlinedb-ffi` lane because
/// the gate is designed to FAIL until workstream B1-B5 ship the in-scope
/// `sqlite3_*` symbols. Run via the dedicated `just ffi-symbol-diff`
/// proof lane, which invokes `cargo test ... -- --ignored`.
#[test]
#[ignore = "run via `just ffi-symbol-diff`; fails by design per parity-closure plan DOD"]
fn libsqlite3_public_surface_is_covered_or_allowlisted() {
    let workspace = workspace_root();
    let reference_path = workspace.join(REFERENCE_PATH);
    let allowlist_path = workspace.join(ALLOWLIST_PATH);

    let reference = load_reference(&reference_path);
    assert!(
        !reference.is_empty(),
        "libsqlite3 reference list at {} is empty",
        reference_path.display()
    );

    let allowlist = load_allowlist(&allowlist_path);
    let dylib = find_dylib(&workspace);
    let exports = dylib_exports(&dylib);

    // Set arithmetic: missing = reference - exports - allowlist
    let missing: BTreeSet<String> = reference
        .iter()
        .filter(|s| !exports.contains(s.as_str()) && !allowlist.contains(s.as_str()))
        .cloned()
        .collect();

    // Always write the baseline so it tracks the current state of the diff,
    // including when the test passes (the baseline shrinks toward zero as
    // workstreams ship). This is informational; the gate is the assertion
    // below.
    let baseline_path = workspace.join(BASELINE_PATH);
    if let Some(parent) = baseline_path.parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    let mut baseline_body = String::new();
    baseline_body.push_str(&format!(
        "# FFI symbol-diff baseline\n\
         # reference: {} ({} symbols)\n\
         # exports:   {} ({} sqlite3_* symbols)\n\
         # allowlist: {} ({} symbols)\n\
         # missing:   {}\n\
         #\n\
         # This file is regenerated on every `just ffi-symbol-diff` run.\n\
         # It is informational; the test fails when `missing` is non-zero AND\n\
         # any missing symbol is not in the allowlist.\n\n",
        reference_path
            .strip_prefix(&workspace)
            .unwrap_or(&reference_path)
            .display(),
        reference.len(),
        dylib
            .strip_prefix(&workspace)
            .unwrap_or(&dylib)
            .display(),
        exports.len(),
        allowlist_path
            .strip_prefix(&workspace)
            .unwrap_or(&allowlist_path)
            .display(),
        allowlist.len(),
        missing.len(),
    ));
    for sym in &missing {
        baseline_body.push_str(sym);
        baseline_body.push('\n');
    }
    let _ = std::fs::write(&baseline_path, baseline_body);

    if !missing.is_empty() {
        let preview: Vec<&String> = missing.iter().take(20).collect();
        let mut msg = String::from(
            "FFI symbol-diff failed: libsqlite3 public symbols are not exported by\n\
             RedlineDB AND not in crates/ffi/tests/symbol_allowlist.toml.\n\
             Fix: either implement the missing symbol in crates/ffi/src/sqlite3_api/\n\
             (preferred) or add an [[exclude]] row with a strict justification per\n\
             the allowlist file header policy.\n\n",
        );
        msg.push_str(&format!(
            "Total missing: {} (showing first {}):\n",
            missing.len(),
            preview.len()
        ));
        for sym in preview {
            msg.push_str("  - ");
            msg.push_str(sym);
            msg.push('\n');
        }
        msg.push_str(&format!(
            "\nFull list written to: {}\n",
            baseline_path
                .strip_prefix(&workspace)
                .unwrap_or(&baseline_path)
                .display()
        ));
        panic!("{msg}");
    }
}
