CREATE TABLE t(id INTEGER, v INTEGER);
CREATE TABLE log(msg TEXT);
CREATE TRIGGER trg AFTER INSERT ON t BEGIN INSERT INTO log VALUES ('inserted'); END;
INSERT INTO t VALUES (1, 10);
SELECT msg FROM log
